inherit_from: .rubocop_todo.yml

require:
  - rubocop-packaging
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable

# Disabled on our repo's to enable polyglot-release
Gemspec/RequireMFA:
  Enabled: false

Layout/LineLength:
  Max: 200
  AllowedPatterns:
    - '^Given'
    - '^When'
    - '^Then'

Style/Documentation:
  Enabled: false

Style/RegexpLiteral:
  EnforcedStyle: slashes
  AllowInnerSlashes: true

RSpec/MessageSpies:
  EnforcedStyle: receive
