rvm:
  - ruby-head
  - 2.4.0
  - 2.3.3
  - 2.2
  - 2.1
  - 2.0

matrix:
  allow_failures:
    - rvm: ruby-head
  fast_finish: true

notifications:
  webhooks:
    urls: # gitter
      - https://webhooks.gitter.im/e/dc010332f9d40fcc21c4
