rvm:
  - ruby-head
  - 2.4.0
  - 2.3.3
  - 2.2
  - 2.1
  - 2.0
  - 1.9.3
  - jruby-1.7.12

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: 1.9.3
    - rvm: jruby-1.7.12
  fast_finish: true

# whitelist
branches:
  only:
    - master

notifications:
  email:
    - cukes-devs@googlegroups.com
  webhooks:
    urls: # gitter
      - https://webhooks.gitter.im/e/dc010332f9d40fcc21c4
