name: Test cucumber-wire

permissions: {}

on:
  push:
    branches:
      - main
      - renovate/**
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 5 * * *"

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest]
        ruby: ['3.2', '3.3', '3.4', '4.0']
        include:
          - os: macos-latest
            ruby: '4.0'
      fail-fast: false

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - uses: ./.github/actions/test-ruby
        with:
          ruby-version: ${{ matrix.ruby }}
